[package]
name = "si-senortn/attribute"
description = "Attribute class"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
set = "si-senortn/set@0.1.0"
Signal = "si-senortn/signal@0.1.0"