[package]
name = "si-senortn/attribute"
description = "Attribute class"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependancies]
set = "si-senortn/set@^0.0"
Signal = "si-senortn/signal@^0.0"