[package]
name = "si-senortn/streamable"
description = "Streamable class"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^1"
Signal = "sleitnick/signal@2.0.1"
