[package]
name = "si-senortn/streamable"
description = "Streamable class"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^1"
Signal = "si-senortn/signal@0.1.0"
