[package]
name = "si-senortn/interpolator"
description = "Interpolator class"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Symbol = "si-senortn/symbol@0.0.2"
strict = "si-senortn/strict@0.0.1"
list = "si-senortn/list@0.0.1"