[package]
name = "senor/interpolator"
description = "Interpolator class"
version = "0.0.1"
authors = ["Luca Fardales"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependancies]
Symbol = "senor/symbol@^0.1"
strict = "senor/strict@^0.1"
list = "senor/list@^0.1"