[package]
name = "si-senortn/enum"
description = "Enum class"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependancies]
Symbol = "si-senortn/symbol@^0.0"