[package]
name = "si-senortn/enum"
description = "Enum class"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Symbol = "si-senortn/symbol@0.0.2"