[package]
name = "si-senortn/color"
description = "Color utility"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependancies]
Math = "si-senortn/math@^0.0"