[package]
name = "si-senortn/config"
description = "Create custom Config types and subscribe to changes"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^0.5"
Symbol = "si-senortn/symbol@0.1.0"
Table = "si-senortn/table@0.1.0"