[package]
name = "si-senortn/config"
description = "Create custom Config types and subscribe to changes"
version = "0.2.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^1"
Symbol = "si-senortn/symbol@0.1.0"
