[package]
name = "si-senortn/events"
description = "Event utility"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Table = "si-senortn/table@0.0.2"
Symbol = "si-senortn/symbol@0.0.2"
strict = "si-senortn/strict@0.0.1"